export const GET_ALL_WOMEN_PAGE_PRODUCTS = 'GET_ALL_WOMEN_PAGE_PRODUCTS';
export const GET_ALL_WOMEN_PAGE_PRODUCTS_SUCCESS =
  'GET_ALL_WOMEN_PAGE_PRODUCTS_SUCCESS';
export const GET_ALL_WOMEN_PAGE_PRODUCTS_ERROR =
  'GET_ALL_WOMEN_PAGE_PRODUCTS_ERROR';
export const WOMEN_PAGE_STATE_UNMOUNT = 'WOMEN_PAGE_STATE_UNMOUNT';

export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR';

export const UPDATE_CART_COUNT_INCREMENT = 'UPDATE_CART_COUNT_INCREMENT';
export const UPDATE_CART_COUNT_DECREMENT = 'UPDATE_CART_COUNT_DECREMENT';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
