export const GET_ALL_WOMEN_PAGE_PRODUCTS = 'GET_ALL_WOMEN_PAGE_PRODUCTS';
export const GET_ALL_WOMEN_PAGE_PRODUCTS_SUCCESS =
  'GET_ALL_WOMEN_PAGE_PRODUCTS_SUCCESS';
export const GET_ALL_WOMEN_PAGE_PRODUCTS_ERROR =
  'GET_ALL_WOMEN_PAGE_PRODUCTS_ERROR';
export const WOMEN_PAGE_STATE_UNMOUNT = 'WOMEN_PAGE_STATE_UNMOUNT';

export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR';
export const ADD_PRODUCT_TO_CART_GUEST = 'ADD_PRODUCT_TO_CART';

export const UPDATE_CART_COUNT_INCREMENT = 'UPDATE_CART_COUNT_INCREMENT';
export const UPDATE_CART_COUNT_DECREMENT = 'UPDATE_CART_COUNT_DECREMENT';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS';
export const GET_CART_ITEMS_ERROR = 'GET_CART_ITEMS_ERROR';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
export const ADD_CART_ITEM_ERROR = 'ADD_CART_ITEM_ERROR';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
export const DELETE_CART_ITEM_ERROR = 'DELETE_CART_ITEM_ERROR';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const DELIVERY_DETAILS_ENTERED = 'DELIVERY_DETAILS_ENTERED';
